web/router.ex
defmodule Forensic.Router do
  use Forensic.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Forensic do
    pipe_through :browser # Use the default browser stack

    resources "/stages", StageController do
      resources "/mirror_params", MirrorParamController, only: [:create, :edit, :update]
      get "/mirror_param/:id/delete", MirrorParamController, :delete
    end

    get "/streams/flush", StreamController, :flush
    get "/avg", AlertController, :avg
    get "/flush_avg", AlertController, :flush_avg

    get "/", PageController, :index
    resources "/alerts", AlertController, only: [:index]
    get "/streams/:id/shock_injection", StreamController, :shock_injection
    get "/streams/:id/stream_creation", StreamController, :stream_creation
    get "/streams/:id/start_streaming", StreamController, :start_streaming
    get "/streams/:id/delete", StreamController, :delete

    resources "/changelog", ChangelogController

    resources "/streams", StreamController do
      resources "/stage_params", StageParamController, only: [:update]
      get "/stages/:stage_id/stage_params", StageParamController, :index
      post "/mirror_params/:mirror_param_id", StageParamController, :create
      get "/stage_param/:id/delete", StageParamController, :delete
    end

  end

  # Other scopes may use custom stacks.
  # scope "/api", Forensic do
  #   pipe_through :api
  # end
end

web/models/stage.ex
defmodule Forensic.Stage do
  use Forensic.Web, :model
  use Ecto.Schema
  use Forensic.AR

  alias Forensic.MirrorParam, as: MP

  schema "stages" do
    field :title, :string
    field :description, :string
    field :script, :string
    field :step, :string
    field :shock_identifier, :string
    has_many :params, MP
    many_to_many :streams, Forensic.Stream, join_through: Forensic.StreamStage

    timestamps()
  end

  def step_icons("store"), do: "download"
  def step_icons("ingestion"), do: "eyedropper"
  def step_icons("process"), do: "industry"
  def step_icons("publish"), do: "sitemap"
  def step_icons(icon), do: "download"

  def changeset(struct, params \\ :empty) do
    struct
    |> cast(params, [:title, :description, :step, :shock_identifier, :script])
    |> validate_required([:title, :step, :shock_identifier])
    |> validate_length(:title, [min: 3, max: 120])
    |> validate_length(:description, [max: 2000])
    |> validate_length(:script, [max: 2000])
  end
end

web/controllers/stage_controller.ex
defmodule Forensic.StageController do
  use Forensic.Web, :controller

  alias Forensic.Stage, as: Stg
  alias Forensic.MirrorParam, as: MP

  @doc """
  List stages created.

  ## Parameters
      - conn: Connection

  ## Examples
      iex> build_conn |> get(:index)
      {:ok, 200}
  """
  @spec index(Plug.Conn.t, Keyword.t) :: Plug.Conn.t
  def index(conn, _) do
    stages = Repo.all Stg, preload: Forensic.Stream
    render conn, "index.html", stages: stages
  end

  def new(conn, changeset: changeset),
    do: render(conn, "new.html", changeset: changeset)
  def new(conn, _params),
    do: new(conn, changeset: Stg.changeset(%Stg{}, %{}))

  def create(conn, %{"stage" => stage_params}) do
    changeset = Stg.changeset(%Stg{}, stage_params)

    case Forensic.Repo.insert(changeset) do
      {:ok, stage} ->
        index(conn, %{})

      {:error, changeset} ->
        new(conn, changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    stage = Repo.get(Stg, id) |> Repo.preload(:params)
    changeset = MP.changeset(%MP{})
    render(conn, "show.html", %{stage: stage, changeset: changeset})
  end

  def delete(conn, %{"id" => id}) do
    stage = Repo.get(Stg, id)
    Repo.delete stage
    index(conn, %{})
  end

  def edit(conn, %{"id" => id}) do
    case Repo.get(Stg, id) do
      stage when is_map(stage) ->
        changeset = Stg.changeset(stage, %{})
        render(conn, "edit.html", %{changeset: changeset, stage: stage})
      _ ->
        show(conn, %{"id" => id})
    end
  end

  def update(conn, %{"id" => id, "stage" => stage_params}) do
    stage = Repo.get(Stg, id)
    changeset = Stg.changeset(stage, stage_params)

    case Repo.update(changeset) do
      {:ok, stage} ->
        conn
        |> put_flash(:info, "Stage updated!")
        |> show(%{"id" => stage.id})

      {:error, changeset} ->
        conn
        |> put_flash(:error, "Invalid attributes!")
        |> edit(changeset: changeset)
    end
  end
end

web/views/stage_view.ex
defmodule Forensic.StageView do
  use Forensic.Web, :view

  def normalize_param_type("1"), do: "string"
  def normalize_param_type("2"), do: "int"
  def normalize_param_type("3"), do: "double"
  def normalize_param_type(_), do: "unknown"
end

web/templates/stage/edit.html.eex
<div class="ui breadcrumb">
  <%= link("Home", to: page_path(@conn, :index), class: "section") %>
  <i class="right angle icon divider"></i>
  <%= link("Stages", to: stage_path(@conn, :index), class: "section") %>
  <i class="right angle icon divider"></i>
  <%= link(@stage.title, to: stage_path(@conn, :show, @stage.id), class: "section") %>
  <i class="right angle icon divider"></i>
  <span class="section">Edit</span>
</div>

<div class="ui middle center aligned grid segment">
  <div class="four wide column">
  </div>
  <div class="four wide column">
    <h1 class="ui teal image header">
      <div class="content">
        Stage Editing
      </div>
    </h1>
    <%= form_for @changeset, stage_path(@conn, :update, @stage), [class: "ui form stages"], fn f -> %>
      <%= if f.errors != [] do %>
        <div class="ui error message">
          <p>Wrong data! :(</p>
        </div>
      <% end %>

      <div class="ui field">
        <div class="ui input">
          <%= text_input f, :title, placeholder: "title" %>
        </div>
      </div>

      <div class="ui field">
        <div class="ui input">
          <%= text_input f, :shock_identifier, placeholder: "Shock function" %>
        </div>
      </div>

      <div class="ui field">
        <div class="ui input">
          <%= textarea  f, :description, placeholder: "description" %>
        </div>
      </div>

      <div class="ui field">
        <div class="ui input">
          <%= textarea  f, :script, placeholder: "script" %>
        </div>
      </div>

      <div class="field">
        <div class="ui inline dropdown">
          <%= hidden_input f, :step %>
          <div class="text">
            Stage step
          </div>
          <i class="dropdown icon"></i>
          <div class="menu">
            <div class="item" data-value="ingestion">
              <i class="eyedropper icon"></i>
              Ingestion
            </div>
            <div class="item" data-value="store">
              <i class="download icon"></i>
              Store
            </div>
            <div class="item" data-value="process">
              <i class="industry icon"></i>
              Process
            </div>
            <div class="item" data-value="publish">
              <i class="sitemap icon"></i>
              Publish
            </div>
          </div>
        </div>
      </div>
      <%= submit "Create stage", class: "ui fluid teal submit button" %>
    <% end %>
  </div>

  <div class="four wide column"></div>
</div>

<div class="ui bottom attached warning message">
  <i class="icon help"></i>
  Confused? Read about stages <%= link("here", to: stage_path(@conn, :index) ) %>.
</div>

web/templates/stage/index.html.eex
<div class="ui breadcrumb">
  <%= link("Home", to: page_path(@conn, :index), class: "section") %>
  <i class="right angle icon divider"></i>
  <span class="section">Stages</span>
</div>

<div class="ui segment">
  <a class="ui green ribbon label" data-content="New feature! Added recently">New</a>
  <h1 class="ui header">Stages</h1>

  <div class="ui middle aligned selection list">
    <%= for st <- @stages do %>
      <div class="item">
        <div class="right floated content">
          <%= link("Remove", to: stage_path(@conn, :delete, st.id), method: :delete, class: "ui button red") %>
        </div>
        <i class="<%= Forensic.Stage.step_icons(st.step) %> icon"></i>
        <div class="content">
          <%= link(st.title, to: stage_path(@conn, :show, st.id), class: "header") %>
          Last Seen 2 days ago
        </div>
      </div>
    <% end %>
  </div>

  <div class="ui labeled button" tabindex="0">
    <%= link("New Stage", to: "/stages/new", class: "ui blue button") %>
    <a class="ui basic blue left pointing label">
      <%= length(@stages) %>
    </a>
  </div>

  <div class="ui left dividing">
    <p class="ui segment">
      Stages are used to compose <%= link("streams", to: stream_path(@conn, :index)) %>.
      Forensic currently supports <strong>4</strong> steps: <strong>ingestion, store, analysis, and publish</strong>.
      After composing a stream, you need to inject it to Shock. For some stages you need to explictly call
      <strong>flush</strong>.
    </p>
  </div>

</div>

web/templates/stage/new.html.eex
<div class="ui middle center aligned grid segment">
  <div class="four wide column">
  </div>
  <div class="four wide column">
    <h1 class="ui teal image header">
      <div class="content">
        New Stage
      </div>
    </h1>
    <%= form_for @changeset, stage_path(@conn, :create), [class: "ui form stages"], fn f -> %>
      <%= if f.errors != [] do %>
        <div class="ui error message">
          <p>Wrong data! :(</p>
        </div>
      <% end %>

      <div class="ui field">
        <div class="ui input">
          <%= text_input f, :title, placeholder: "title" %>
        </div>
      </div>

      <div class="ui field">
        <div class="ui input">
          <%= text_input f, :shock_identifier, placeholder: "shock identifier" %>
        </div>
      </div>

      <div class="ui field">
        <div class="ui input">
          <%= textarea  f, :description, placeholder: "description" %>
        </div>
        <%= error_tag f, :description %>
      </div>

      <div class="ui field">
        <div class="ui input">
          <%= textarea  f, :script, placeholder: "script" %>
        </div>
        <%= error_tag f, :script %>
      </div>

      <div class="field">
        <div class="ui inline dropdown">
          <%= hidden_input f, :step %>
          <div class="text">
            Stage step
          </div>
          <i class="dropdown icon"></i>
          <div class="menu">
            <div class="item" data-value="ingestion">
              <i class="eyedropper icon"></i>
              Ingestion
            </div>
            <div class="item" data-value="store">
              <i class="download icon"></i>
              Store
            </div>
            <div class="item" data-value="process">
              <i class="industry icon"></i>
              Process
            </div>
            <div class="item" data-value="publish">
              <i class="sitemap icon"></i>
              Publish
            </div>
          </div>
        </div>
      </div>
      <%= submit "Create stage", class: "ui fluid teal submit button" %>
    <% end %>
  </div>

  <div class="four wide column"></div>
</div>

<div class="ui bottom attached warning message">
  <i class="icon help"></i>
  Confused? Read about stages <%= link("here", to: stage_path(@conn, :index) ) %>.
</div>

web/templates/stage/show.html.eex
<div class="ui breadcrumb">
  <%= link("Home", to: page_path(@conn, :index), class: "section") %>
  <i class="right angle icon divider"></i>
  <%= link("Stages", to: stage_path(@conn, :index), class: "section") %>
  <i class="right angle icon divider"></i>
  <span class="section"><%= @stage.title %></span>
</div>

<div class="ui vertical stripe segment">
  <div class="ui middle center aligned stackable grid container">
    <h1>
      <%= @stage.title %>
    </h1>
  </div>

  <div class="ui grid">
    <div class="eight wide column">
      <div class="ui items">
        <div class="ui item">
          <div class="image">
          </div>
          <div class="content">
            <h2 class="ui header"><%= @stage.shock_identifier %></h2>
            <%= @stage.step %> stage
            <div class="meta">
              <%= @stage.description %>
            </div>
          </div>
        </div>
      </div>

      <div class="ui statistics middle center aligned container">
        <div class="statistic">
          <div class="value">
            22
          </div>
          <div class="label">
            Faves
          </div>
        </div>
        <div class="statistic">
          <div class="value">
            31,200
          </div>
          <div class="label">
            Views
          </div>
        </div>
        <div class="statistic">
          <div class="value">
            22
          </div>
          <div class="label">
            Members
          </div>
        </div>
      </div>


      <div class="ui inverted center aligned segment">
        <%= link("Edit", to: stage_path(@conn, :edit, @stage.id), class: "ui inverted button") %>
      </div>

    </div>

    <div class="eight wide column">
      <div class="ui segment">
        <h2 class="ui header">Params</h2>

        <table class="ui inverted teal celled table">
          <thead>
            <tr>
              <th>Param</th>
              <th>Type</th>
              <th>Required</th>
              <th>Actions</th>
            </tr>
          </thead>

          <tbody>
            <%= for p <- @stage.params do %>
              <tr>
                <td><%= p.title %></td>
                <td><%= normalize_param_type(p.param_type) %></td>
                <td><%= p.required? %></td>
                <td class="center aligned">
                  <div class="ui small icon buttons">
                    <a href="<%= stage_mirror_param_path(@conn, :edit, @stage.id, p.id) %>" class="white ui button">
                      <i class="configure icon"></i>
                    </a>
                    <a href="<%= stage_mirror_param_path(@conn, :delete, @stage.id, p.id) %>" class="red ui button">
                      <i class="remove icon"></i>
                    </a>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <h4 class="ui header">New Param</h4>
        <%= form_for @changeset, stage_mirror_param_path(@conn, :create, @stage.id), [class: "ui form"], fn f -> %>
          <%= if f.errors != [] do %>
            <div class="ui error message">
              <p>Wrong data! :(</p>
            </div>
          <% end %>

          <div class="ui field">
            <div class="ui input">
              <%= text_input f, :title, placeholder: "title" %>
            </div>
            <%= error_tag f, :title %>
          </div>

          <div class="ui field">
            <%= select f, :param_type, [{"string", 1}, {"int", 2}, {"double", 3}], class: "ui fluid search dropdown" %>
          </div>

          <div class="ui field">
            <div class="ui checked checkbox">
              <%= checkbox f, :required?, class: "checkbox" %>
              <label>Required?</label>
            </div>
          </div>

          <%= submit "Create param", class: "ui fluid teal submit button" %>
        <% end %>
      </div>

      <div class="ui segment">
        <div class="title">
          Script
        </div>
        <div class="content">
          <%= @stage.script %>
        </div>
      </div>
    </div>
  </div>
</div>