web/router.ex
defmodule Forensic.Router do
  use Forensic.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Forensic do
    pipe_through :browser # Use the default browser stack

    resources "/stages", StageController do
      resources "/mirror_params", MirrorParamController, only: [:create, :edit, :update]
      get "/mirror_param/:id/delete", MirrorParamController, :delete
    end

    get "/streams/flush", StreamController, :flush
    get "/avg", AlertController, :avg
    get "/flush_avg", AlertController, :flush_avg

    get "/", PageController, :index
    resources "/alerts", AlertController, only: [:index]
    get "/streams/:id/shock_injection", StreamController, :shock_injection
    get "/streams/:id/stream_creation", StreamController, :stream_creation
    get "/streams/:id/start_streaming", StreamController, :start_streaming
    get "/streams/:id/delete", StreamController, :delete

    resources "/changelog", ChangelogController

    resources "/streams", StreamController do
      resources "/stage_params", StageParamController, only: [:update]
      get "/stages/:stage_id/stage_params", StageParamController, :index
      post "/mirror_params/:mirror_param_id", StageParamController, :create
      get "/stage_param/:id/delete", StageParamController, :delete
    end

  end

  # Other scopes may use custom stacks.
  # scope "/api", Forensic do
  #   pipe_through :api
  # end
end

web/models/stream.ex
defmodule Forensic.Stream do
  @moduledoc """
  * Entity that represents Streams.

  ## Usage

      iex> Forensic.Stream.changeset(%Forensic.Stream, %{name: "My pipeline"})
      nil

  ## Attributes
      * name: Stream name
      * description: Stream description
  """

  use Forensic.Web, :model
  use Ecto.Schema

  alias Forensic.MirrorParam, as: MP
  alias Forensic.Repo
  alias Forensic.StageParam, as: SP
  alias Forensic.Stream, as: S
  alias Forensic.StreamStage, as: SS
  alias Forensic.Stage, as: Stg

  import Ecto.Changeset

  use Forensic.AR

  @typedoc """
  Stream struct

  ## Attributes
      * name
      * description
  """
  @type t :: %Forensic.Stream{}

  schema "streams" do
    field :name, :string
    field :description, :string
    field :injected?, :boolean
    field :created?, :boolean
    many_to_many :stages, Forensic.Stage, join_through: Forensic.StreamStage

    timestamps()
  end

  @spec changeset(t, map) :: t
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :created?, :injected?, :description])
    |> validate_required([:name])
    |> unique_constraint(:name)
    |> validate_length(:name, [min: 3, max: 120])
    |> validate_length(:description, [max: 2000])
  end

  @spec shock_injection(t) :: t
  def shock_injection(stream) do
    stages = stream.stages
    stages_ids = stages |> Enum.map(fn (item) -> item.id end)
    selected_params = (from p in SP, where: p.stream_id == ^stream.id, preload: :stage) |> Repo.all
    for p <- stages do
      file = p.step <> ";"
      selected_params =
        (from p in SP, where: p.stage_id==^p.id and p.stream_id==^stream.id, preload: :mirror)
        |> Repo.all

      selected_params = Enum.reduce(selected_params, %{}, fn(param, acc) ->
        Enum.into(%{"#{param.mirror.title}" => param.value}, acc) end)

      selected_params = Map.merge(selected_params, %{
        "shock_action" => p.shock_identifier, "stream" => String.replace(stream.name, " ", "")
      })

      args = Poison.encode!(selected_params)
      KafkaEx.produce("new_pipeline_instruction", 0, file <> args)
    end
  end

  def kafka_create_stream(stream) do
    args = %{"stream" => String.replace(stream.name, " ", "")} |> Poison.encode!
    payload = "newStream;"<>args
    KafkaEx.produce("new_pipeline_instruction", 0, payload)
    toggle_created_attr(stream)
  end

  @doc """
  Toggle the boolean value of the `created?` attr.

  ## Parameters
      - stream : Related stream.
  
  ## Examples
      iex> stream = Repo.get(Forensic.Stream, 1)
      iex> stream.created?
      false
      iex> Forensic.Stream.toggle_created_attr(stream)
      :ok
      iex> stream = Repo.get(Forensic.Stream, 1)
      iex> stream.created?
      true 
  """
  @spec toggle_created_attr(t) :: :ok
  def toggle_created_attr(stream) do
    changeset = S.changeset(stream, %{"created?" => not stream.created?})
    Repo.update changeset
    :ok
  end

  @doc """
  Creates Shock stream.

  If the stream is already created, it is destroyed.

  ## Parameters
      - stream : Related stream.

  ## Examples
      iex> stream = Repo.get(Forensic.Stream, 1)
      iex> Forensic.Stream.create_shock_stream(stream)
      => Kafka's message sent
  """
  @spec create_shock_stream(t) :: atom
  def create_shock_stream(stream) do
    created? = stream.created?
    case created? do
      true ->
        toggle_created_attr(stream)
      false ->
        kafka_create_stream(stream)
    end
  end

  @doc """
  Tells Shock to start the streaming.

  ## Parameters
      - stream: Stream that will be started.

  ## Examples
      iex> stream = Repo.get(Forensic.Stream, 1)
      Forensic.Stream{...}
      iex> Forensic.Stream.start_streaming(stream)
      => Kafka's message sent
  """
  @spec start_streaming(t) :: :ok
  def start_streaming(stream) do
    payload = %{"stream" => String.replace(stream.name, " ", "")} |> Poison.encode!
    KafkaEx.produce("new_pipeline_instruction", 0, "start;"<>payload)
    :ok
  end

  @doc """
  Relate every stage_id with the given stream.

  ## Parameters
      - stream: A stream already inserted in the Repo.
      - stages_ids: List of stages that will be related.


  ## Examples
      iex> length(Repo.all(Forensic.StreamStage))
      0
      iex> Forensic.Stream.add_stages(stream, [1,2,3])
      :ok
      iex> length(Repo.all(Forensic.StreamStage))
      3
  """
  @spec add_stages(t, :error) :: nil
  def add_stages(stream, :error), do: :nil
  @spec add_stages(t, List.t) :: :ok
  def add_stages(stream, {:ok, stages_ids}) do
    for stage_id <- stages_ids do
      stream_stage = SS.relate(stage_id, stream.id)
      {:ok, _} = Repo.insert(stream_stage)
    end
    :ok
  end

  def missing_parameters?(stream) do
    IO.warn("DEPRECATED. This method will be renamed in the future.")
    stages_ids = (from u in SS, where: u.stream_id==^stream.id, select: u.stage_id) |> Repo.all
    mp = (from u in MP, where: u.stage_id in ^stages_ids and u.required?==true, select: u.id) |> Repo.all
    sp = (from u in SP, where: u.mirror_id in ^mp and u.stream_id==^stream.id, select: u.mirror_id) |> Repo.all
    Enum.sort(mp) != Enum.sort(sp)
  end

  def configuration_pending?([]), do: true
  def configuration_pending?(array), do: false
  def configuration_pending?(stream, mp) do
    q = (from p in SP, where: p.stream_id == ^stream.id and p.mirror_id == ^mp.id)
    result = Repo.all q
    configuration_pending?(result)
  end

  def related_params(stream, stage) do
    q = from p in SP, where: p.stream_id==^stream.id and p.stage_id==^stage.id, preload: :mirror
    Repo.all q
  end

  def flush(params) do
    args = Poison.encode!(params)
    KafkaEx.produce("new_pipeline_instruction", 0, "flush;"<>args)
  end
end

web/controllers/stream_controller.ex
defmodule Forensic.StreamController do
  @moduledoc """
  Handles stream-related requests.
  """

  use Forensic.Web, :controller

  alias Forensic.Stream, as: S
  alias Forensic.Repo
  alias Forensic.Stage, as: Stg
  alias Forensic.StreamStage, as: SS
  alias Forensic.StageParam, as: SP

  @doc """
  List created streams.

  ## Parameters
      - conn: Related connection.

  ## Examples
      iex> build_conn() |> get(:index)
      {:ok, 200}
  """
  @spec index(Plug.Conn.t, Keyword.t) :: Plug.Conn.t
  def index(conn, _params) do
    streams = S.all
    render conn, "index.html", streams: streams
  end

  def new(conn, changeset: changeset),
    do: render(conn, "new.html", %{changeset: changeset, stages: Stg.all})
  def new(conn, _params),
    do: new(conn, changeset: S.build)

  def create(conn, %{"stream" => stream_params}) do
    changeset = S.build(stream_params)
    stages = Map.fetch(stream_params, :stages_ids)

    case S.save(changeset) do
      {:ok, stream} ->
        S.add_stages(stream, Map.fetch(stream_params, "stages_ids"))
        index(conn, %{})

      {:error, changeset} ->
        new(conn, changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    stream = S.find(id) |> Repo.preload :stages
    stream_stages = SS.all
    stream_params = (from u in SP, where: u.stream_id==^id, preload: :mirror) |> Repo.all
    render(conn, "show.html", %{stream: stream, stream_stages: stream_stages, stream_params: stream_params})
  end

  def update(conn, %{"id" => id, "stream" => stream_params}) do
    stream = Repo.get(S, id)
    changeset = S.changeset(stream, stream_params)
    case Repo.update(changeset) do
      {:ok, stream} ->
        S.add_stages(stream, Map.fetch(stream_params, "stages_ids"))
        conn
        |> put_flash(:info, "Stream updated!")
        |> show(%{"id" => stream.id})

      {:error, changeset} ->
        conn
        |> put_flash(:error, "Invalid attributes!")
        |> edit(%{"id" => id, changeset: changeset})
    end
  end

  def edit(conn, %{"id" => id, changeset: changeset}) do
    case Repo.get(S, id) do
      stream when is_map(stream) ->
        stages = Repo.all Stg
        render(conn, "edit.html", %{changeset: changeset, stream: stream, stages: stages})
      _ ->
        show(conn, %{"id" => id})
    end
  end
  def edit(conn, %{"id" => id}) do
    stream = Repo.get(S, id)
    changeset = S.changeset(stream, %{})
    edit(conn, %{"id" => id, changeset: changeset})
  end

  def shock_injection(conn, %{"id" => id}) do
    stream = Repo.get(S, id) |> Repo.preload(:stages)
    injected? = stream.injected?
    if not injected? do
      S.shock_injection(stream)
    end
    changeset = S.changeset(stream, %{injected?: not injected?})
    case Repo.update changeset do
      {:ok, stream} ->
        conn
        |> put_flash(:info, "Stream updated!")
        |> show(%{"id" => stream.id})

      {:error, changeset} ->
        conn
        |> put_flash(:error, "Invalid attributes!")
        |> show(%{"id" => stream.id})
    end
  end

  def stream_creation(conn, %{"id" => id}) do
    stream = Repo.get(S, id)
    S.create_shock_stream(stream)
    show(conn, %{"id" => id})
  end

  def start_streaming(conn, %{"id" => id}) do
    stream = Repo.get(S, id)
    S.start_streaming(stream)
    conn
    |> put_flash(:warning, "Your stream started to run!")
    |> show(%{"id" => id})
  end

  def delete(conn, %{"id" => id}) do
    stream = Repo.get(S, id)
    Repo.delete stream
    index(conn, %{})
  end

  def flush(conn, _) do
    Repo.delete_all Forensic.Report
    KafkaEx.produce("new_pipeline_instruction", 0, "flush;{}")

    conn
    |> redirect(to: alert_path(conn, :index))
  end
end

web/views/stream_view.ex
defmodule Forensic.StreamView do
  use Forensic.Web, :view

  alias Forensic.StageParam, as: SP
  alias Forensic.MirrorParam, as: MP
  alias Forensic.Repo
  alias Forensic.Stream, as: S

  import Ecto.Query, only: [from: 2]

  def boolean_to_color(true), do: "green"
  def boolean_to_color(_), do: "red"

  def boolean_to_text(true, text), do: text
  def boolean_to_text(_, text), do: "Not "<>text

  def check_stage(stream, step) do
    cond1 = stream.created?
    cond2 = not S.missing_parameters?(stream)
    cond3 = stream.injected?

    steps = %{
      "0" => true,
      "1" => cond1,
      "2" => cond1 and cond2,
      "3" => cond1 and cond2 and cond3,
      "4" => false
    }

    previous_step = String.to_integer(step) |> Kernel.-(1) |> Integer.to_string

    case Map.get(steps, step) do
      true ->
        case Map.get(steps, previous_step) do
          true ->
            "completed"
          _ ->
            "disabled"
        end

      _ ->
        case Map.get(steps, previous_step) do
          true ->
            "active"
          _ ->
            "disabled"
        end
    end
  end

  def required_title(true), do: "R"
  def required_title(_), do: "O"

  def required_label(true), do: "red"
  def required_label(_), do: "blue"

  def required_tooltip(true), do: "This param is required!"
  def required_tooltip(_), do: "This param is optional."
end

web/templates/stream/edit.html.eex
<div class="ui breadcrumb">
  <%= link("Home", to: page_path(@conn, :index), class: "section") %>
  <i class="right angle icon divider"></i>
  <%= link("Streams", to: stream_path(@conn, :index), class: "section") %>
  <i class="right angle icon divider"></i>
  <%= link(@stream.name, to: stream_path(@conn, :show, @stream.id), class: "section") %>
  <i class="right angle icon divider"></i>
  <span class="section">Edit</span>
</div>

<div class="ui middle center aligned grid segment">
  <div class="four wide column">
  </div>
  <div class="four wide column">
    <h1 class="ui teal image header">
      <div class="content">
        Stream editing
      </div>
    </h1>
    <%= form_for @changeset, stream_path(@conn, :update, @stream), [class: "ui form streams"], fn f -> %>
      <%= if f.errors != [] do %>
        <div class="ui error message">
          <p>Wrong data! :(</p>
        </div>
      <% end %>

      <div class="ui field">
        <div class="ui input">
          <%= text_input f, :name, placeholder: "name" %>
        </div>
      </div>

      <div class="ui field">
        <div class="ui input">
          <%= textarea  f, :description, placeholder: "description" %>
        </div>
      </div>

      <div class="ui field">
        <%= multiple_select f, :stages_ids, @stages |> Enum.map(&{&1.title, &1.id}), class: "ui fluid search dropdown" %>
      </div>

      <%= submit "Edit stream", class: "ui fluid teal submit button" %>
    <% end %>
  </div>
  <div class="four wide column">
  </div>
</div>

web/templates/stream/index.html.eex
<div class="ui breadcrumb">
  <%= link("Home", to: page_path(@conn, :index), class: "section") %>
  <i class="right angle icon divider"></i>
  <span class="section">Streams</span>
</div>

<div class="ui segment">
  <a class="ui green ribbon label" data-content="New feature! Added recently">New</a>
  <h1 class="ui header">Streams</h1>

  <div class="ui divided items">
    <%= for st <- @streams do %>
      <div class="item">
        <div class="content">
          <%= link(st.name, to: stream_path(@conn, :show, st.id), class: "header") %>
          <div class="description">
            <p><%= st.description %></p>
          </div>
          <div class="extra">
            <div class="ui small buttons">
              <%= link("Edit", to: stream_path(@conn, :edit, st.id), class: "ui blue button") %>
              <%= link("Delete", to: stream_path(@conn, :delete, st.id), class: "ui red button") %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="ui labeled button" tabindex="0">
    <%= link("New Stream", to: "/streams/new", class: "ui blue button") %>
    <a class="ui basic blue left pointing label">
      <%= length(@streams) %>
    </a>
  </div>
</div>

web/templates/stream/new.html.eex
<div class="ui middle center aligned grid segment">
  <div class="four wide column">
  </div>
  <div class="four wide column">
    <h1 class="ui teal image header">
      <div class="content">
        New Stream
      </div>
    </h1>

    <%= form_for @changeset, stream_path(@conn, :create), [class: "ui form streams"], fn f -> %>
      <%= if f.errors != [] do %>
        <div class="ui error message">
          <p>Wrong data! :(</p>
        </div>
      <% end %>

      <div class="ui field">
        <div class="ui input">
          <%= text_input f, :name, placeholder: "name" %>
        </div>
      </div>

      <div class="ui field">
        <div class="ui input">
          <%= textarea  f, :description, placeholder: "description" %>
        </div>
      </div>

      <div class="ui field">
        <%= multiple_select f, :stages_ids, @stages |> Enum.map(&{&1.title, &1.id}), class: "ui fluid search dropdown" %>
      </div>

      <%= submit "Create stream", class: "ui fluid teal submit button" %>
    <% end %>
  </div>
  <div class="four wide column">
  </div>
</div>

web/templates/stream/pipeline.html.eex
<h2 class="ui header center aligned">Pipeline</h2>

<table class="ui celled table">
  <thead>
    <tr>
      <th>Stage</th>
      <th>Description</th>
      <th>Parameters</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <%= for stg <- @stream.stages do %>
      <tr>
        <td><%= link(stg.title, to: stage_path(@conn, :show, stg.id)) %></td>
        <td><%= stg.description %></td>
        <td>
          <%= for p <- Forensic.Stream.related_params(@stream, stg) do %>
            <div class="ui image <%= required_label(p.mirror.required?) %> label">
              <span class="activator" data-title="Value" data-content="<%= p.value %>"><%= p.mirror.title %></span>
              <%= link to: stream_stage_param_path(@conn, :delete, @stream.id, p.id), class: "" do %>
                <i class="delete icon remove-parameter-icon"></i>
              <% end %>
              <div class="detail" data-tooltip="<%= required_tooltip(p.mirror.required?) %>">
                <%= required_title(p.mirror.required?) %>
              </div>
            </div>
          <% end %>
        </td>

        <td>
          <%= link("Edit Params", to: stream_stage_param_path(@conn, :index, @stream.id, stg.id), class: "tiny ui button") %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

web/templates/stream/show.html.eex
<div class="ui breadcrumb">
  <%= link("Home", to: page_path(@conn, :index), class: "section") %>
  <i class="right angle icon divider"></i>
  <%= link("Streams", to: stream_path(@conn, :index), class: "section") %>
  <i class="right angle icon divider"></i>
  <span class="active section"><%= @stream.name %></span>
</div>

<div class="ui vertical stripe segment">
  <div class="ui container">
    <div class="column">

      <h1 class="ui header center aligned"><%= @stream.name %></h1>

      <%= render "stream_steps.html", %{conn: @conn, stream: @stream} %>
    </div>
  </div>

  <div class="ui segment">

    <%= if Forensic.Stream.missing_parameters?(@stream) do %>
      <a class="activator ui yellow left corner label">
        <i class="ellipsis vertical icon"></i>
      </a>

      <div class="ui flowing popup top left transition hidden">
        <h4>There are required parameters not filled!</h4>
        <p>
          You should configure required parameters. Check the "Edit Params" action.
        </p>
      </div>
    <% end %>

    <%= render "pipeline.html", %{conn: @conn, stream: @stream} %>

    <div class="ui inverted center aligned segment">
      <%= link("Edit Pipeline", to: stream_path(@conn, :edit, @stream.id), class: "ui inverted button") %>
      <%= link("Shock Injection", to: stream_path(@conn, :shock_injection, @stream.id), class: "ui inverted teal button") %>
      <%= link("Delete Stream", to: stream_path(@conn, :delete, @stream.id), class: "ui red button") %>
    </div>
  </div>
</div>

web/templates/stream/stream_steps.html.eex
<div class="container">
  <div class="ui tiny fluid ordered steps">
    <div class="<%= check_stage(@stream, "1") %> step">
      <div class="content">
        <%= link("Create Stream", to: stream_path(@conn, :stream_creation, @stream.id), class: "title") %>
        <div class="description">Create the stream for Shock usage.</div>
      </div>
    </div>

    <div class="<%= check_stage(@stream, "2") %> step">
      <div class="content">
        <a class="title">Configure Streams</a>
        <div class="description">Configure stream params to be used by Shock.</div>
      </div>
    </div>

    <div class="<%= check_stage(@stream, "3") %> step">
      <div class="content">
        <%= link("Inject pipeline", to: stream_path(@conn, :shock_injection, @stream.id), class: "title") %>
        <div class="description">Inject stages in Shock's stream.</div>
      </div>
    </div>

    <div class="<%= check_stage(@stream, "4") %> step">
      <div class="content">
        <%= link("Start streaming", to: stream_path(@conn, :start_streaming, @stream.id), class: "title") %>
        <div class="description">Start the stream.</div>
      </div>
    </div>
  </div>
</div>