web/router.ex
defmodule Forensic.Router do
  use Forensic.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Forensic do
    pipe_through :browser # Use the default browser stack

    resources "/stages", StageController do
      resources "/mirror_params", MirrorParamController, only: [:create, :edit, :update]
      get "/mirror_param/:id/delete", MirrorParamController, :delete
    end

    get "/streams/flush", StreamController, :flush
    get "/avg", AlertController, :avg
    get "/flush_avg", AlertController, :flush_avg

    get "/", PageController, :index
    resources "/alerts", AlertController, only: [:index]
    get "/streams/:id/shock_injection", StreamController, :shock_injection
    get "/streams/:id/stream_creation", StreamController, :stream_creation
    get "/streams/:id/start_streaming", StreamController, :start_streaming
    get "/streams/:id/delete", StreamController, :delete

    resources "/changelog", ChangelogController

    resources "/streams", StreamController do
      resources "/stage_params", StageParamController, only: [:update]
      get "/stages/:stage_id/stage_params", StageParamController, :index
      post "/mirror_params/:mirror_param_id", StageParamController, :create
      get "/stage_param/:id/delete", StageParamController, :delete
    end

  end

  # Other scopes may use custom stacks.
  # scope "/api", Forensic do
  #   pipe_through :api
  # end
end

web/models/changelog.ex
defmodule Forensic.Changelog do
  @moduledoc """
  * Entity that represents new Changelogs in the platform.

  ## Usage

      iex> Forensic.Changelog.changeset(%Forensic.Changelog, %{description: "My descript"})
      nil

  ## Attributes
      * description: Stream description
  """

  use Forensic.Web, :model
  use Ecto.Schema

  import Ecto.Changeset

  use Forensic.AR

  @typedoc """
  Changelog struct

  ## Attributes
      * description
  """
  @type t :: %Forensic.Changelog{}

  schema "changelogs" do
    field :description, :string

    timestamps()
  end

  @spec changeset(t, map) :: t
  def changeset(struct, params \\ :empty) do
    struct
    |> cast(params, [:description])
    |> validate_required([:description])
    |> validate_length(:description, [max: 2000])
  end
end

web/controllers/changelog_controller.ex
defmodule Forensic.ChangelogController do
  use Forensic.Web, :controller

  alias Forensic.Changelog

  def index(conn, _) do
    changelogs = Changelog.all
    render conn, "index.html", changelogs: changelogs
  end

  def new(conn, changeset: changeset),
    do: render(conn, "new.html", changeset: changeset)
  def new(conn, _params),
    do: new(conn, changeset: Changelog.build)

  def create(conn, %{"changelog" => changelog_params}) do
    changeset = Changelog.build(changelog_params)

    case Changelog.save(changeset) do
      {:ok, changelog} ->
        index(conn, %{})

      {:error, changeset} ->
        new(conn, changeset: changeset)
    end
  end
end

web/views/changelog_view.ex
defmodule Forensic.ChangelogView do
  use Forensic.Web, :view
end

web/templates/changelog/index.html.eex
<div class="ui segment">
  <h1>Changelogs</h1>

  <table class="ui celled table">
    <thead>
      <tr>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      <%= for clog <- @changelogs do %>
        <tr>
          <td><%= clog.description %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="ui labeled button" tabindex="0">
    <%= link("New", to: "/changelog/new", class: "ui blue button") %>
    <a class="ui basic blue left pointing label">
      <%= length(@changelogs) %>
    </a>
  </div>
</div>

web/templates/changelog/new.html.eex
<div class="ui middle aligned center aligned grid segment">
  <div class="column">
    <h1 class="ui teal image header">
      <div class="content">
        New Changelog
      </div>
    </h1>
    <%= form_for @changeset, changelog_path(@conn, :create), [class: "ui form"], fn f -> %>
      <%= if f.errors != [] do %>
        <div class="ui error message">
          <p>Wrong data! :(</p>
        </div>
      <% end %>

      <div class="ui field">
        <div class="ui input">
          <%= textarea f, :description, placeholder: "Description" %>
        </div>
        <%= error_tag f, :description %>
      </div>

      <%= submit "Create changelog", class: "ui fluid teal submit button" %>
    <% end %>
  </div>
</div>